import Head from 'next/head';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>user API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <h2>"Тестовое задание"</h2>
        <p>"Task Description. @Требуется разработать API сервис для хранения пользователей"</p>
      </main>
    </>
  )
}

export default HomePage
