import Head from 'next/head'
import Navbar from '@/components/Navbar'
import GetTextFromLocalDB from "../models/localModelDB"

const HomePage = () => {
  return (
    <>
      <Head>
        <title>user API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h2>{GetTextFromLocalDB[0].homePageTitle}</h2>
        <p>{GetTextFromLocalDB[0].homePageDescription}</p>
    </main>
    </>
  )
}

export default HomePage
